### PR TITLE
fix(transformData): Pass state as one of the parameter to transformData

### PR DESCRIPTION
**Pull request by rahulchakraborty91**
Pass state as one of the parameter to transformData 

## Description
 As a part of this PR, I'm passing state as one of the parameter to  transformData function.

## Motivation and Context
 This is required since we need to refer state for few things while transforming the data

## How Has This Been Tested?
 Tested locally 

## Types of Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (adding or updating documentation)
- [ ] Dependency update

## Checklist:

- [x] My change requires a change to the documentation and I have updated the documentation accordingly.
- [x] My changes are in sync with the code style of this project.
- [x] There aren't any other open Pull Requests for the same issue/update.
- [ ] These changes should be applied to a maintenance branch.
- [ ] I have added the Apache 2.0 license header to any new files created.

## What is the Impact to Developers Using Iguazu-Rest?
No Impact.

### CODE REVIEW

**Comment by Matthew-Mallimo** [comment]
Please fill out the PR description

**Comment by rahulchakraborty91** [comment]
> Please fill out the PR description

@Matthew-Mallimo Added.

**Review by JAdshead — APPROVED** [review]

**Review by 10xLaCroixDrinker — CHANGES_REQUESTED** [review]
Please update test cases, otherwise LGTM

**Comment by 10xLaCroixDrinker** [comment]
closing for inactivity. feel free to reopen when ready to make the requested changes

**Pull request closed without merging**
