### PR TITLE
[fix] fix minor typo in readme

### PR DESCRIPTION
**Pull request by seankwon**
### Description

Just adding a few curly boys

### CODE REVIEW

**Comment by seankwon** [comment]
oops, i need to sign the cla. i'll get to that tomorrow

**Comment by mtomcal** [comment]
@seankwon Any love on our CLA? We appreciate your contribution!

**Comment by seankwon** [comment]
@mtomcal it says i signed it, but for some reason, it remains pending... :(

**Comment by anescobar1991** [comment]
@seankwon it says the email address your commit is associated with is not on your github account. That’s why the CLA is still unsigned.

Can you add that email address to your github account?

**Comment by seankwon** [comment]
i decided to just do a reset since my old commits were linked to invalid email address

**Comment by seankwon** [comment]
sorry for the wait, @mtomcal @10xLaCroixDrinker ya'll can review this again.

**Pull request merged**
